# Generated by Django 5.1.3 on 2024-11-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pekerja',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nama_bank', models.CharField()),
                ('nomor_rekening', models.CharField()),
                ('npwp', models.CharField()),
                ('link_foto', models.URLField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('level', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nama', models.CharField()),
                ('jenis_kelamin', models.CharField(max_length=1)),
                ('noHp', models.CharField()),
                ('password', models.CharField()),
                ('tanggal_lahir', models.DateField()),
                ('alamat', models.CharField()),
                ('saldo_mypay', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
